server:
  port: 8000

spring:
  application:
    name: 'post-service'
  datasource:
    url: ${DB_URL:jdbc:postgresql://35.223.44.11:5432/reserve}
    username: ${DB_USERNAME:reserve1}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}

validationServer: ${VALIDATION}