---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postservice-deployment
  template:
    metadata:
      labels:
        app: postservice-deployment
    spec:
      containers:
      - image: keoffor/post-service:latest
        env:
          - name: VALIDATION
            value: http://34.122.231.247:8081/users/validate
          - name: EUREKA_URI
            value: http://35.223.118.158:8083/eureka
          - name: ANGULAR_URI
            value: http://34.122.103.73:80
          - name: AWS_ACCESS_KEY
            value: AKIA4OK5FKIY3WZXH4XW
          - name:  AWS_SECRET_KEY
            value: 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
        imagePullPolicy: Always
        name: postservicecontainer
        ports: 
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postservice-service
  name: postservice
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-postservice
      port: 8000
      targetPort: 8000
  selector:
    app: postservice-deployment
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: post-service-monitor
spec:
  selector:
    matchLabels:
      app: postservice-service
  endpoints:
    - port: http-app1
      path: "/actuator/prometheus"







